apiVersion: v2
appVersion: 1.0.0
description: The web client for the Github contributions in Jordan. 
home: https://github.com/jordanopensource/contributions-web
keywords:
  - nuxt
  - javascript
  - vue
  - frontend
maintainers:
  - email: admin@josa.ngo
    name: Jordan Open Source Association
name: contributions-web
version: 1.0.1
icon: https://d2zv2ciw0ln4h1.cloudfront.net/uploads/hp-logo-hero_c94026101f.svg
