apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "label-studio.fullname" .}}-config
data:
  DJANGO_DB: "default"
  POSTGRE_HOST: {{ .Values.postgres.host | quote }}
  POSTGRE_PORT: {{ .Values.postgres.port | quote }}
  POSTGRE_NAME: {{ .Values.postgres.database | quote }}
  POSTGRE_USER: {{ .Values.postgres.username | quote }}
  LABEL_STUDIO_HOST: {{ .Values.app.host | quote }}
{{- if .Values.app.restrictSignUp.enabled }}
  LABEL_STUDIO_DISABLE_SIGNUP_WITHOUT_LINK: "true"
{{- end }}
{{- range $key, $value := .Values.extraEnv }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
