# Default values for mailman.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

# Postgresql database
postgresql:
  internal: true
  postgresqlHost: ""
  postgresqlPort: ""
  postgresqlDatabase: mailman
  postgresqlUsername: postgres
  postgresqlPassword: secret
  existingSecret: {}
    # secretName: mailman-secret
    # databaseUrlKey: databaseUrl  # "postgres://username:password@host:port/database"

# Application settings
mailman:
  domainName: lists.example.com
  hostName: mail.lists.example.com
  apiKey: verySecretApiKey
  secretKey: verySecretKey
  adminUser: admin
  adminEmail: admin@example.com
  existingSecret: {}
    # secretName: mailman-secret
    # adminUserKey: adminUser
    # apiKey: apiKey
    # secretKey: secretKey
    # adminEmailKey: adminEmail

# Certificate manager
certmanager:
  issuerType: ClusterIssuer
  issuerName: letsencrypt

# Mailman Core
core:
  service:
    type: ClusterIP
    ports:
      api: 8001
      lmtp: 8024
      postfixExtender: 5000
    annotations: {}

  replicaCount: 1

  image:
    registry: docker.io
    repository: maxking/mailman-core
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""

  podAnnotations: {}
  podSecurityContext: {}
  securityContext: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  resources: {}

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80

  persistence:
    enabled: false
    annotations: {}
    accessModes: 
      - ReadWriteOnce
    size: 1Gi
    storageClass: ""

  secretNamesForExtraEnv: []
  extraEnv: {}

  livenessProbe:
    enabled: false
    initialDelaySeconds: 0
    successThreshold: 1
    failureThreshold: 3
    timeoutSeconds: 1
    periodSeconds: 10

  readinessProbe:
    enabled: false
    initialDelaySeconds: 0
    successThreshold: 1
    failureThreshold: 3
    timeoutSeconds: 1
    periodSeconds: 10

  postfixExtender:
    image:
      registry: docker.io
      repository: danilsmirnov/mailman-postfix-extender
      pullPolicy: IfNotPresent
      tag: latest
    securityContext: {}
    resources: {}

    secretNamesForExtraEnv: []
    extraEnv:
      FILES: "/opt/mailman/var/data/postfix_domains,/opt/mailman/var/data/postfix_lmtp"

    livenessProbe:
      enabled: false
      initialDelaySeconds: 0
      successThreshold: 1
      failureThreshold: 3
      timeoutSeconds: 1
      periodSeconds: 10

    readinessProbe:
      enabled: false
      initialDelaySeconds: 0
      successThreshold: 1
      failureThreshold: 3
      timeoutSeconds: 1
      periodSeconds: 10

      
# Mailman Web
web:
  withHyperkitty: true

  image:
    registry: docker.io
    repository: maxking/mailman-web
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""

  postorius:
    image:
      registry: docker.io
      repository: maxking/postorius
      pullPolicy: IfNotPresent
      # Overrides the image tag whose default is the chart appVersion.
      tag: ""

  service:
    type: ClusterIP
    ports:
      api: 8000
      http: 80
    annotations: {}

  ingress:
    enabled: false
    className: ""
    annotations: {}
    hosts:
      - host: mailmanweb.local
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls: []

  replicaCount: 1
  podAnnotations: {}
  podSecurityContext: {}
  securityContext: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  resources: {}

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80

  persistence:
    enabled: false
    annotations: {}
    accessModes: 
      - ReadWriteOnce
    size: 1Gi
    storageClass: ""

  secretNamesForExtraEnv: []
  extraEnv: {}

  livenessProbe:
    enabled: false
    initialDelaySeconds: 0
    successThreshold: 1
    failureThreshold: 3
    timeoutSeconds: 1
    periodSeconds: 10

  readinessProbe:
    enabled: false
    initialDelaySeconds: 0
    successThreshold: 1
    failureThreshold: 3
    timeoutSeconds: 1
    periodSeconds: 10

  extraConfig: |
    HAYSTACK_CONNECTIONS = {
      'default': {
          'ENGINE': 'xapian_backend.XapianEngine',
          'PATH': "/opt/mailman-web-data/fulltext_index",
      },
    }
    import dj_database_url
    DATABASES = {
        'default': dj_database_url.config(conn_max_age=0)
    }
    ACCOUNT_DEFAULT_HTTP_PROTOCOL = "http"

  nginx:
    image:
      registry: docker.io
      repository: nginx
      pullPolicy: IfNotPresent
      tag: 1.21
    securityContext: {}
    resources: {}
    secretNamesForExtraEnv: []
    extraEnv: {}

    livenessProbe:
      enabled: false
      initialDelaySeconds: 0
      successThreshold: 1
      failureThreshold: 3
      timeoutSeconds: 1
      periodSeconds: 10

    readinessProbe:
      enabled: false
      initialDelaySeconds: 0
      successThreshold: 1
      failureThreshold: 3
      timeoutSeconds: 1
      periodSeconds: 10

# Postfix
postfix:
  subnet: ""
  dkimSecret: false
  certSecret: false
  debugMode: false

  username: mailman
  password: secret
  existingSecret: {}
    # secretName: mailman-secret
    # passwordKey: postfixPassword
    # usernameKey: postfixUser
    # usernameAndPasswordKey: postfixUserAndPassword # Use this format "username:password" 

  relay:
    enabled: false
    host: relay.example.com
    port: 587
    username: username
    password: secret
    existingSecret: {}
      # secretName: mailman-secret
      # usernameKey: relayUser
      # passwordKey: relayPassword

  service:
    type: LoadBalancer
    externalTrafficPolicy: Local
    ports:
      smtp: 25
      tls: 587
    annotations: {}

  replicaCount: 1
  
  image:
    registry: docker.io
    repository: danilsmirnov/postfix
    pullPolicy: IfNotPresent
    tag: 1.7

  podAnnotations: {}
  podSecurityContext: {}
  securityContext: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  resources: {}

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80

  persistence:
    enabled: false
    annotations: {}
    accessModes: 
      - ReadWriteOnce
    size: 10Gi
    storageClass: ""

  secretNamesForExtraEnv: []
  extraEnv: {}

  livenessProbe:
    enabled: false
    initialDelaySeconds: 0
    successThreshold: 1
    failureThreshold: 3
    timeoutSeconds: 1
    periodSeconds: 10

  readinessProbe:
    enabled: false
    initialDelaySeconds: 0
    successThreshold: 1
    failureThreshold: 3
    timeoutSeconds: 1
    periodSeconds: 10
