# Default values for mailman.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

# Postgresql database
postgresql:
  internal: true
  postgresqlHost: ""
  postgresqlPort: ""
  postgresqlDatabase: mailman
  postgresqlUsername: postgres
  postgresqlPassword: secret
  existingSecret: {}
    # secretName: mailman-secret
    # databaseUrlKey: databaseUrl  # "postgres://username:password@host:port/database"

# Global
global:
  adminEmail: ""
  domainName: lists.example.com
  hostName: mail.lists.example.com

# Certificate manager
certmanager:
  issuerType: ClusterIssuer
  issuerName: letsencrypt

# Mailman Core
core:
  service:
    type: ClusterIP
    ports:
      api: 8001
      postfixExtender: 5000

  replicaCount: 1

  image:
    repository: maxking/mailman-core
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""

  podAnnotations: {}
  podSecurityContext: {}
  securityContext: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  resources: {}

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80

  persistence:
    enabled: false
    annotations: {}
    accessModes: 
      - ReadWriteOnce
    size: 1Gi
    storageClass: ""

  secretNamesForEnv: []
  env:
    DATABASE_TYPE: postgres
    DATABASE_CLASS: "mailman.database.postgresql.PostgreSQLDatabase"

  postfixExtender:
    image:
      repository: danilsmirnov/mailman-postfix-extender
      pullPolicy: IfNotPresent
      tag: latest
    securityContext: {}
    resources: {}

    secretNamesForEnv: []
    env:
      FILES: "/opt/mailman/var/data/postfix_domains,/opt/mailman/var/data/postfix_lmtp"

      
# Mailman Web
web:
  withHyperkitty: true

  image:
    repository: maxking/mailman-web
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""

  postorius:
    image:
      repository: maxking/postorius
      pullPolicy: IfNotPresent
      # Overrides the image tag whose default is the chart appVersion.
      tag: ""

  service:
    type: ClusterIP
    ports:
      api: 8000
      http: 80

  ingress:
    enabled: true
    className: ""
    annotations: {}
    hosts:
      - host: mailmanweb.local
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls: []

  replicaCount: 1
  podAnnotations: {}
  podSecurityContext: {}
  securityContext: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  resources: {}

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80

  persistence:
    enabled: false
    annotations: {}
    accessModes: 
      - ReadWriteOnce
    size: 1Gi
    storageClass: ""

  secretNamesForEnv: []
  env: {}

  nginx:
    image:
      repository: nginx
      pullPolicy: IfNotPresent
      tag: latest
    securityContext: {}
    resources: {}
    secretNamesForEnv: []
    env: {}


# Postfix
postfix:
  subnet: ""
  dkimSecret: false
  certSecret: false
  debugMode: false

  username: mailman
  password: secret
  existingSecret: {}
    # secretName: mailman-secret
    # passwordKey: postfixPassword
    # usernameKey: postfixUser
    # usernameAndPasswordKey: postfixUserAndPassword # Use this format "username:password" 

  relay:
    enabled: false
    host: relay.example.com
    port: 587
    username: username
    password: secret
    existingSecret: {}
      # secretName: mailman-secret
      # usernameKey: relayUser
      # passwordKey: relayPassword

  service:
    type: LoadBalancer
    externalTrafficPolicy: Local
    ports:
      smtp: 25
      tls: 587

  replicaCount: 1
  
  image:
    repository: danilsmirnov/postfix
    pullPolicy: IfNotPresent
    tag: 1.7

  podAnnotations: {}
  podSecurityContext: {}
  securityContext: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  resources: {}

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80

  persistence:
    enabled: false
    annotations: {}
    accessModes: 
      - ReadWriteOnce
    size: 10Gi
    storageClass: ""


  secretNamesForExtraEnv: []
  extraEnv: {}
