# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
fullnameOverride: "" 

# Contributors CRON
name: contributors-cron
image:
  repository: josaorg/top-contributors-cron
  tag: latest
  imagePullPolicy: Always
# CRON job schedule
schedule: "* * * * *"
resources:
  limits:
    cpu: 50m
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 256Mi
failedJobsHistoryLimit: 1
successfulJobsHistoryLimit: 3
concurrencyPolicy: Forbid
restartPolicy: Never
tolerations:
  - effect: NoSchedule
    operator: Exists
# DataBase certificate
certificate:
  enabled: false
  path: /app/cert
  secret: secret-name

configMapNamesforEnv: []

secretNamesForEnv: []

nodeSelector: {}

# Enviornemnt variables
env: 
  NODE_ENV: development
  # DB_URL:
  # GITHUB_API_KEY:

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""