default_stages:
  - pre-commit
repos:
  - repo: meta
    hooks:
      - id: check-useless-excludes
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: detect-private-key
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-json
        types: ["json"]
      - id: pretty-format-json
        types: ["json"]
        args:
          - "--autofix"
          - "--no-sort-keys"
      # - id: check-yaml
      #   args: [--allow-multiple-documents]
      #   exclude: ^charts/*/templates/$
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.30
    hooks:
      - id: helmlint
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.28.0
    hooks:
      - id: gitleaks
        name: detect hardcoded secrets
