apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "monk.fullname" . }}
  labels:
    {{- include "monk.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "monk.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "monk.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "monk.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if .Values.listmonk.freshInstall}}
      initContainers:
        - name: init-db
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          command: ["./listmonk", "--install", "--yes"]
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.existingSecret.enabled}}
          env:
            - name: LISTMONK_app__admin_username
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.existingSecret.secretName }}
                  key: {{ .Values.existingSecret.adminUsernameKey }}
            - name: LISTMONK_app__admin_password
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.existingSecret.secretName }}
                  key: {{ .Values.existingSecret.adminPasswordKey }}
            - name: LISTMONK_db__password
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.existingSecret.secretName }}
                  key: {{ .Values.existingSecret.databasePasswordKey }}
          {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "monk.fullname" . }}
          {{- if not .Values.existingSecret.enabled }}
            - secretRef:
                name: {{ include "monk.fullname" . }}
          {{- end }}
          {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          {{- if .Values.listmonk.upgrade}}
          command: ["./listmonk", "--upgrade", "--yes"]
          {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.existingSecret.enabled}}
          env:
            - name: LISTMONK_app__admin_username
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.existingSecret.secretName }}
                  key: {{ .Values.existingSecret.adminUsernameKey }}
            - name: LISTMONK_app__admin_password
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.existingSecret.secretName }}
                  key: {{ .Values.existingSecret.adminPasswordKey }}
            - name: LISTMONK_db__password
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.existingSecret.secretName }}
                  key: {{ .Values.existingSecret.databasePasswordKey }}
          {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "monk.fullname" . }}
            {{- if not .Values.existingSecret.enabled }}
            - secretRef:
                name: {{ include "monk.fullname" . }}
            {{- end }}
          ports:
            - name: http
              containerPort: 9090
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
