apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "monk.fullname" . }}
  labels:
    {{- include "monk.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "monk.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "monk.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "monk.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: db-check
          image: {{ include "monk.image" . | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/bin/sh", "-c"]
          args:
            - "./listmonk --install --idempotent --yes --config '' && ./listmonk --upgrade --yes --config ''"
          {{- with include "monk.secretEnv" . | trim }}
          env:
            {{- . | nindent 12 }}
          {{- end }}
          envFrom:
            {{- include "monk.envFrom" . | nindent 12 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ include "monk.image" . | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with include "monk.secretEnv" . | trim }}
          env:
            {{- . | nindent 12 }}
          {{- end }}
          envFrom:
            {{- include "monk.envFrom" . | nindent 12 }}
          ports:
            - name: http
              containerPort: 9090
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
