apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "monk.fullname" . }}
  labels:
    {{- include "monk.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "monk.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "monk.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "monk.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            # - name: LISTMONK_app__address
            #   value: "0.0.0.0:9000"
            - name: LISTMONK_app__admin_username
              value: monk
            - name: LISTMONK_app__admin_password
              value: monk
            - name: LISTMONK_db__host
              value: "postgresql-db-jordanopensource-org-do-user-1737715-0.b.db.ondigitalocean.com"
            - name: LISTMONK_db__port
              value: "25060"
            - name: LISTMONK_db__user
              value: monk
            - name: LISTMONK_db__password
              value: "s2iozQWmFkdxRmkI"
            - name: LISTMONK_db__database
              value: monk
            - name: LISTMONK_db__ssl_mode
              value: "require"
          command: ["yes| ./listmonk"]
          args: ["--install"]
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
