apiVersion: v1
kind: Secret
metadata:
  name: {{ include "monk.fullname" . }}
  labels:
{{ include "monk.labels" . | indent 4 }}
data:
{{- if not .Values.existingSecret.enabled }}
  LISTMONK_db__password: {{ .Values.listmonk.database.credentials.password | b64enc }}
  LISTMONK_app__admin_username: {{ .Values.listmonk.adminCredentials.username | b64enc }}
  LISTMONK_app__admin_password: {{ .Values.listmonk.adminCredentials.password | b64enc }}
{{- end }}
{{ range $key, $value := .Values.env.private }}
  {{ $key }}: {{ $value | b64enc }}
{{- end -}}
