apiVersion: v2
name: uwazi
annotations:
  category: Applications
description: Uwazi helm chart
home: https://josa.ngo
icon: https://assets.josacdn.net/brand/josa/logos/abbreviated/josa-logo-only.png
keywords:
  - uwazi
maintainers:
  - name: JOSA
    url: https://github.com/jordanopensource/charts/
sources:
  - https://github.com/jordanopensource/charts/tree/main/charts/uwazi

version: 1.0.1
appVersion: "0.1.0"

dependencies:
  - name: base
    alias: uwazi
    version: "~1.2.0"
    repository: "https://charts.josa.ngo"
  - name: mongodb
    version: "~16.3.0"
    repository: "https://charts.bitnami.com/bitnami"
    condition: mongodb.create
  - name: redis
    version: "~20.4.0"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.create
  - name: minio
    version: "~14.8.5"
    repository: "https://charts.bitnami.com/bitnami"
    condition: minio.create
  - name: elasticsearch
    version: "~21.3.26"
    repository: "https://charts.bitnami.com/bitnami"
    condition: elasticsearch.create
