{{- if not .Values.existingSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "etherpad.fullname" . }}
  labels:
{{ include "etherpad.labels" . | indent 4 }}
data:
  ADMIN_PASSWORD: {{ .Values.general.adminCredentials.password | b64enc }}
  USER_PASSWORD: {{ .Values.general.userPassword | b64enc }}
  DB_PASS: {{ .Values.database.credentials.dbPassword | b64enc }}
  OPENID_CLIENT_SECRET: {{ .Values.openID.clientSecret | b64enc }}
{{- end }}