{{- if and .Values.persistence.data.enabled .Values.persistence.data.hostPath -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "common.names.fullname" . }}-gophish
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  {{- if not (empty .Values.persistence.data.accessModes) }}
  accessModes:
  {{- range .Values.persistence.data.accessModes }}
    - {{ . | quote }}
  {{- end }}
  {{- end }}
  capacity:
    storage: {{ .Values.persistence.data.size | quote }}
  hostPath:
    path: {{ .Values.persistence.data.hostPath | quote }}
{{- end -}}
