
{{- if and .Values.persistence.data.enabled -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "common.names.fullname" . }}-data
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- if or .Values.persistence.data.annotations .Values.commonAnnotations }}
  {{- $annotations := include "common.tplvalues.merge" ( dict "values" ( list .Values.persistence.data.annotations .Values.commonAnnotations ) "context" . ) }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" $annotations "context" $) | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.persistence.data.hostPath }}
  storageClassName: ""
  {{- else }}
  {{- include "gophish.storageClass" . | nindent 2 }}
  {{- end }}
  {{- if not (empty .Values.persistence.data.accessModes) }}
  accessModes:
  {{- range .Values.persistence.data.accessModes }}
    - {{ . | quote }}
  {{- end }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.data.size | quote }}
  {{- if .Values.persistence.data.selector }}
  selector: {{- include "common.tplvalues.render" (dict "value" .Values.persistence.data.selector "context" $) | nindent 4 }}
  {{- end -}}
  {{- if .Values.persistence.data.dataSource }}
  dataSource: {{- include "common.tplvalues.render" (dict "value" .Values.persistence.data.dataSource "context" $) | nindent 4 }}
  {{- end }}
{{- end -}}
