apiVersion: v2
name: gophish
description: gophish helm chart for Kubernetes
type: application
version: 1.0.0
appVersion: 0.9.0
maintainers:
  - email: admin@josa.ngo
    name: Jordan Open Source Association
