apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mastodon.fullname" . }}-web
  labels:
    {{- include "mastodon.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "mastodon.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: web
      app.kubernetes.io/part-of: rails
  template:
    metadata:
      annotations:
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
        # roll the pods to pick up any db migrations
        rollme: {{ randAlphaNum 5 | quote }}
      labels:
        {{- include "mastodon.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: web
        app.kubernetes.io/part-of: rails
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "mastodon.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if (not .Values.s3.enabled) }}
      volumes:
        - name: assets
          persistentVolumeClaim:
            claimName: {{ template "mastodon.fullname" . }}-assets
        - name: system
          persistentVolumeClaim:
            claimName: {{ template "mastodon.fullname" . }}-system
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - bundle
            - exec
            - puma
            - -C
            - config/puma.rb
          envFrom:
            - configMapRef:
                name: {{ include "mastodon.fullname" . }}-config
            - secretRef:
                name: {{ .Values.mastodon.secrets.secretName }}
            - secretRef:
                name: {{ .Values.postgres.credentials.secretName }}
            - secretRef:
                name: {{ .Values.redis.secretName }}
            - secretRef:
                name: {{ .Values.smtp.credentials.secretName }}
          {{- if .Values.s3.enabled }}
            - secretRef:
                name: {{ .Values.s3.credentials.secretName }}
          {{- end }}
          {{- if .Values.elasticsearch.credentials.enabled }}
            - secretRef:
                name: {{ .Values.elasticsearch.credentials.secretName }}
          {{- end }}
          {{- if .Values.ldap.enabled }}
            - secretRef:
                name: {{ .Values.ldap.credentials.secretName }}
          {{- end }}
          env:
            - name: "PORT"
              value: {{ .Values.mastodon.web.port | quote }}
          {{- if (not .Values.s3.enabled) }}
          volumeMounts:
            - name: assets
              mountPath: /opt/mastodon/public/assets
            - name: system
              mountPath: /opt/mastodon/public/system
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.mastodon.web.port }}
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: {{ .Values.mastodon.web.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.mastodon.web.livenessProbe.periodSeconds }}
            # One second longer than command timeout should prevent generation of zombie processes.
            timeoutSeconds: {{ add1 .Values.mastodon.web.livenessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.mastodon.web.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.mastodon.web.livenessProbe.failureThreshold }}
            httpGet:
              path: /health
              port: http
          readinessProbe:
            initialDelaySeconds: {{ .Values.mastodon.web.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.mastodon.web.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ add1 .Values.mastodon.web.readinessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.mastodon.web.readinessProbe.successThreshold }}
            failureThreshold: {{ .Values.mastodon.web.readinessProbe.failureThreshold }}
            httpGet:
              path: /health
              port: http
          {{- if .Values.postgres.credentials.certificateSecret }}
          volumeMounts:
            - name: certificates
              mountPath: "/opt/mastodon/.postgresql"
              readOnly: true
          {{- end }}
          resources:
            {{- toYaml .Values.mastodon.web.resources | nindent 12 }}
      {{- with .Values.mastodon.web.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.postgres.credentials.certificateSecret }}
      volumes:
      - name: certificates
        secret:
          secretName: {{ .Values.postgres.credentials.certificateSecret }}
          items:
          - key: db-certificate.crt
            path: root.crt
      {{- end }}
