{{- if (not .Values.mastodon.s3.enabled) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "mastodon.fullname" . }}-assets
  labels:
    {{- include "mastodon.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.mastodon.persistence.system.accessMode }}
  resources:
    {{- toYaml .Values.mastodon.persistence.assets.resources | nindent 4}}
  storageClassName: {{ .Values.mastodon.persistence.assets.storageClassName }}
{{- end }}
