{{- if .Values.workload.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "base.names.fullname" . }}
  namespace: {{ include "base.names.namespace" . | quote }}
  labels: {{- include "base.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: {{ .Values.workload.type }}
    name: {{ include "base.names.fullname" . }}
  minReplicas: {{ .Values.workload.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.workload.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.workload.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.workload.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.workload.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.workload.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
