{{- if .Values.workload.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "base.serviceAccountName" . }}
  namespace: {{ include "base.names.namespace" . | quote }}
  labels: {{- include "base.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- if or .Values.workload.serviceAccount.annotations .Values.commonAnnotations }}
  {{- $annotations := include "base.tplvalues.merge" ( dict "values" ( list .Values.workload.serviceAccount.annotations .Values.commonAnnotations ) "context" . ) }}
  annotations: {{- include "base.tplvalues.render" ( dict "value" $annotations "context" $) | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.workload.serviceAccount.automount }}
{{- end }}