apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "matomo.fullname" . }}-env
  labels:
    {{- include "matomo.labels" . | nindent 4 }}
data:
{{- range $envKey, $envVal := .Values.env }}
  {{ $envKey | upper }}: {{ $envVal | quote }}
{{- end }}
{{- if .Values.mysql.enabled }}
{{- include "matomo.mysql.env" . | nindent 2 }}
{{- end }}
