{{- if .Values.proxy.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "snowflake.fullname-proxy" . }}
  labels:
    {{- include "snowflake.labels-proxy" . | nindent 4 }}
spec:
  replicas: {{ .Values.proxy.replicaCount }}
  selector:
    matchLabels:
      {{- include "snowflake.selectorLabels-proxy" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.proxy.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "snowflake.selectorLabels-proxy" . | nindent 8 }}
    spec:
      {{- with .Values.proxy.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ .Values.proxy.serviceAccount.name }}
      securityContext:
        {{- toYaml .Values.proxy.podSecurityContext | nindent 8 }}
      hostNetwork: true
      containers:
        - name: {{ .Chart.Name }}-proxy
          securityContext:
            {{- toYaml .Values.proxy.securityContext | nindent 12 }}
          image: "{{ .Values.proxy.image.repository }}:{{ .Values.proxy.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.proxy.image.pullPolicy }}
          args:
            - '-broker'
            - {{ .Values.proxy.settings.brokerURL }}
            - '-capacity'
            - '500'
            {{ if .Values.proxy.settings.keepLocalAddress }}
            - '-keep-local-addresses'
            {{ end }}
            {{ if .Values.proxy.settings.unsafeLogging }}
            - '-unsafe-logging'
            {{ end }}
            {{ if .Values.proxy.settings.relayURL }}
            - '-relay'
            - {{ .Values.proxy.settings.relayURL }}
            {{ end }}
            {{ if .Values.proxy.settings.stunURL }}
            - '-stun'
            - {{ .Values.proxy.settings.stunURL }}
            {{ end }}
          resources:
            {{- toYaml .Values.proxy.resources | nindent 12 }}
      {{- with .Values.proxy.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.proxy.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.proxy.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
