{{- if .Values.proxy.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "snowflake.serviceAccountName-proxy" . }}
  labels:
    {{- include "snowflake.labels-proxy" . | nindent 4 }}
  {{- with .Values.proxy.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
