apiVersion: v1
kind: Service
metadata:
  name: {{include "snowflake.fullname-web" .}}
  labels: {{- include "snowflake.labels-web" . | nindent 4}}
spec:
  type: {{.Values.web.service.type}}
  ports:
    - port: {{.Values.web.service.port}}
      targetPort: http
      protocol: TCP
      name: http
  selector: {{- include "snowflake.selectorLabels-web" . | nindent 4}}
