{{- if .Values.web.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "snowflake.serviceAccountName-web" . }}
  labels:
    {{- include "snowflake.labels-web" . | nindent 4 }}
  {{- with .Values.web.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
