apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "monica.fullname" . }}-env
  labels:
    {{- include "monica.labels" . | nindent 4 }}
data:
{{- if .Values.mysql.enabled }}
  DB_HOST: {{- include "monica.mysql.fullname" -}}
  DB_PORT: 3306
{{- end }}
{{- range $envKey, $envVal := .Values.env }}
  {{ $envKey | upper }}: {{ $envVal | quote }}
{{- end }}
