apiVersion: v1
kind: Service
metadata:
  name: {{ include "wazuh.fullname" . }}-cluster
  labels:
    app: {{ include "wazuh.fullname" . }}-manager
    {{- include "wazuh.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 1516
      targetPort: 1516
      protocol: TCP
      name: cluster
  selector:
    app: {{ include "wazuh.fullname" . }}-manager
    {{- include "wazuh.selectorLabels" . | nindent 4 }}
