{{- if not .Values.manager.config.secrets.existingSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name:  {{ include "wazuh.fullname" . }}-manager
type: Opaque
data:
  API_PASSWORD: {{ .Values.manager.config.secrets.wazuhApiPassword | b64enc }}
  API_USERNAME: {{ .Values.manager.config.secrets.wazuhApiUsername | b64enc }}
  INDEXER_PASSWORD: {{ .Values.manager.config.secrets.indexerPassword | b64enc }}
  INDEXER_USERNAME: {{ .Values.manager.config.secrets.indexerUsername | b64enc }}
  WAZUH_CLUSTER_KEY: {{ .Values.manager.config.secrets.wazuhClusterKey | b64enc }}
  authd.pass: {{ .Values.manager.config.secrets.wazuhAuthDPass | b64enc }}
{{- end }}
