apiVersion: v1
kind: Service
metadata:
  name: {{ include "wazuh.fullname" . }}-manager
  labels:
    app: {{ include "wazuh.fullname" . }}-manager
    {{- include "wazuh.labels" . | nindent 4 }}
  {{- with .Values.manager.service.annotations }}
  annotations:
    {{- toYaml . | nindent 8 }}
  {{- end }}
spec:
  type: {{ .Values.manager.service.type }}
  ports:
    - port: 1515
      targetPort: 1515
      protocol: TCP
      name: registration
    - port: 1514
      targetPort: 1514
      protocol: TCP
      name: agents-events
    - port: 55000
      targetPort: 55000
      protocol: TCP
      name: api
  selector:
    app: {{ include "wazuh.fullname" . }}-manager
    {{- include "wazuh.selectorLabels" . | nindent 4 }}