apiVersion: v1
kind: Service
metadata:
  name: {{ include "wazuh.fullname" . }}-workers
  labels:
    app: {{ include "wazuh.fullname" . }}-manager
    {{- include "wazuh.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 1514
      targetPort: 1514
      protocol: TCP
      name: agents-events
  selector:
    app: {{ include "wazuh.fullname" . }}-manager
    node-type: worker
    {{- include "wazuh.selectorLabels" . | nindent 4 }}
