{{- if not .Values.indexer.config.indexerCustomConfig }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "wazuh.fullname" . }}-indexer-config
data:
{{ (.Files.Glob "indexer_conf/opensearch.yml").AsConfig | indent 2 }}
{{- end }}
