apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "wazuh.fullname" . }}-indexer
  labels:
    {{- include "wazuh.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.indexer.replicaCount }}
  serviceName: {{ include "wazuh.fullname" . }}-indexer
  selector:
    matchLabels:
      app: {{ include "wazuh.fullname" . }}-indexer
      {{- include "wazuh.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.indexer.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: {{ include "wazuh.fullname" . }}-indexer
        {{- include "wazuh.labels" . | nindent 8 }}
        {{- with .Values.indexer.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.indexer.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.indexer.priorityClassName }}
      priorityClassName: {{ .Values.indexer.priorityClassName }}
      {{- end }}
      serviceAccountName: {{ include "wazuh.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.indexer.podSecurityContext | nindent 8 }}
      initContainers:
        - name: volume-mount-hack
          image: busybox
          resources:
            {{- toYaml .Values.indexer.initContainers.resources | nindent 12 }}
          env:
            - name: RUN_AS_USER
              value: {{ .Values.indexer.initContainers.runAsUser | quote }}
            - name: RUN_AS_GROUP
              value: {{ .Values.indexer.initContainers.runAsGroup | quote }}
          command:
            - sh
            - '-c'
            - |
              chown -R $RUN_AS_USER:$RUN_AS_GROUP /var/lib/wazuh-indexer
          securityContext:
            runAsUser: {{ .Values.indexer.initContainers.runAsUser }}
            runAsGroup: {{ .Values.indexer.initContainers.runAsGroup }}
          volumeMounts:
            - name: wazuh-indexer
              mountPath: /var/lib/wazuh-indexer
        - name: increase-the-vm-max-map-count
          image: busybox
          command:
            - sysctl
            - -w
            - vm.max_map_count=262144
          securityContext:
            {{- toYaml .Values.indexer.initContainers.securityContext | nindent 12 }}
      containers:
        - name: {{ include "wazuh.fullname" . }}-indexer
          securityContext:
            {{- toYaml .Values.indexer.securityContext | nindent 12 }}
          image: "{{ .Values.indexer.image.repository }}:{{ .Values.indexer.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.indexer.image.pullPolicy }}
          {{- if .Values.indexer.config.envFromConfigMap }}
          envFrom:
            - configMapRef:
                name: {{ .Values.indexer.config.envFromConfigMap }}
          {{- end }}
          env:
            - name: OPENSEARCH_JAVA_OPTS
              value: {{ .Values.indexer.config.javaOpts | quote }}
            - name: CLUSTER_NAME
              value: {{ include "wazuh.fullname" . }}
            - name: NETWORK_HOST
              value: {{ .Values.indexer.config.networkHost | quote }}
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: DISCOVERY_SERVICE
              value: {{ include "wazuh.fullname" . }}-indexer
            - name: SECURITY_AUTHCZ_ADMIN_DN
              value: {{ .Values.tls.certManager.commonName }}
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: HTTP_SSL_ENABLED
              value: {{ .Values.indexer.config.sslEnabled | quote }}
            - name: DISABLE_INSTALL_DEMO_CONFIG
              value: "true"
            - name: INDEXER_USERNAME
              valueFrom:
                secretKeyRef:
                  {{- if .Values.manager.config.secrets.existingSecretName }}
                  name: {{ .Values.manager.config.secrets.existingSecretName }}
                  {{- else }}
                  name: {{ include "wazuh.fullname" . }}-manager
                  {{- end }}
                  key: INDEXER_USERNAME
            - name: INDEXER_PASSWORD
              valueFrom:
                secretKeyRef:
                  {{- if .Values.manager.config.secrets.existingSecretName }}
                  name: {{ .Values.manager.config.secrets.existingSecretName }}
                  {{- else }}
                  name: {{ include "wazuh.fullname" . }}-manager
                  {{- end }}
                  key: INDEXER_PASSWORD
          ports:
            - name: indexer-api
              protocol: TCP
              containerPort: 9200
            - name: indexer-nodes
              containerPort: 9300
              protocol: TCP
          {{- if .Values.indexer.probes.liveness.enabled }}
          livenessProbe:
            exec:
              command:
              - sh
              - '-c'
              - |
                curl -k -u $INDEXER_USERNAME:$INDEXER_PASSWORD https://localhost:9200/_cluster/health
            initialDelaySeconds: {{ .Values.indexer.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.indexer.probes.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.indexer.probes.liveness.timeoutSeconds }}
            failureThreshold: {{ .Values.indexer.probes.liveness.failureThreshold }}
          {{- end }}
          {{- if .Values.indexer.probes.readiness.enabled }}
          readinessProbe:
            exec:
              command:
              - sh
              - '-c'
              - |
                curl -k -u $INDEXER_USERNAME:$INDEXER_PASSWORD https://localhost:9200/_cluster/health
            initialDelaySeconds: {{ .Values.indexer.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.indexer.probes.readiness.periodSeconds }}
            timeoutSeconds: {{ .Values.indexer.probes.readiness.timeoutSeconds }}
            failureThreshold: {{ .Values.indexer.probes.readiness.failureThreshold }}
          {{- end }}
          resources:
            {{- if .Values.indexer.resourceValidation.enabled }}
            {{- $resources := .Values.indexer.resources }}
            {{- if $resources.requests }}
              {{- if $resources.requests.memory }}
                {{- if lt (regexReplaceAll "[^0-9]" $resources.requests.memory "") (regexReplaceAll "[^0-9]" .Values.indexer.resourceValidation.minMemory "") }}
                  {{- fail (printf "Memory request (%s) is below minimum allowed (%s)" $resources.requests.memory .Values.indexer.resourceValidation.minMemory) }}
                {{- end }}
              {{- end }}
              {{- if $resources.requests.cpu }}
                {{- if lt (regexReplaceAll "[^0-9]" $resources.requests.cpu "") (regexReplaceAll "[^0-9]" .Values.indexer.resourceValidation.minCPU "") }}
                  {{- fail (printf "CPU request (%s) is below minimum allowed (%s)" $resources.requests.cpu .Values.indexer.resourceValidation.minCPU) }}
                {{- end }}
              {{- end }}
            {{- end }}
            {{- if $resources.limits }}
              {{- if $resources.limits.memory }}
                {{- if gt (regexReplaceAll "[^0-9]" $resources.limits.memory "") (regexReplaceAll "[^0-9]" .Values.indexer.resourceValidation.maxMemory "") }}
                  {{- fail (printf "Memory limit (%s) is above maximum allowed (%s)" $resources.limits.memory .Values.indexer.resourceValidation.maxMemory) }}
                {{- end }}
              {{- end }}
              {{- if $resources.limits.cpu }}
                {{- if gt (regexReplaceAll "[^0-9]" $resources.limits.cpu "") (regexReplaceAll "[^0-9]" .Values.indexer.resourceValidation.maxCPU "") }}
                  {{- fail (printf "CPU limit (%s) is above maximum allowed (%s)" $resources.limits.cpu .Values.indexer.resourceValidation.maxCPU) }}
                {{- end }}
              {{- end }}
            {{- end }}
            {{- end }}
            {{- toYaml .Values.indexer.resources | nindent 12 }}
          volumeMounts:
            - name: wazuh-indexer
              mountPath: /var/lib/wazuh-indexer
            - name: indexer-conf
              mountPath: /usr/share/wazuh-indexer/opensearch.yml
              subPath: opensearch.yml
              readOnly: true
            - name: indexer-users
              mountPath: /usr/share/wazuh-indexer/opensearch-security/internal_users.yml
              subPath: internal_users.yml
              readOnly: true
            - name: indexer-certs
              mountPath: /usr/share/wazuh-indexer/certs/node-key.pem
              subPath: node-key.pem
              readOnly: true
            - name: indexer-certs
              mountPath: /usr/share/wazuh-indexer/certs/node.pem
              subPath: node.pem
              readOnly: true
            - name: indexer-certs
              mountPath: /usr/share/wazuh-indexer/certs/root-ca.pem
              subPath: root-ca.pem
              readOnly: true
            - name: indexer-certs
              mountPath: /usr/share/wazuh-indexer/certs/admin.pem
              subPath: admin.pem
              readOnly: true
            - name: indexer-certs
              mountPath: /usr/share/wazuh-indexer/certs/admin-key.pem
              subPath: admin-key.pem
              readOnly: true
            {{- with .Values.indexer.volumeMounts }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
      volumes:
        {{- if .Values.tls.certManager.enabled }}
        - name: indexer-certs
          projected:
            sources:
            - secret:
                name: {{ .Values.tls.certManager.caCrtSecretName }}
                items:
                  - key: ca.crt
                    path: root-ca.pem
            - secret:
                name: admin-tls
                items:
                  - key: tls.crt
                    path: admin.pem
                  - key: tls.key
                    path: admin-key.pem
            - secret:
                name: node-tls
                items:
                  - key: tls.crt
                    path: node.pem
                  - key: tls.key
                    path: node-key.pem
            - secret:
                name: filebeat-tls
                items:
                  - key: tls.crt
                    path: filebeat.pem
                  - key: tls.key
                    path: filebeat-key.pem
        {{- else if .Values.tls.secretName }}
        - name: indexer-certs
          secret:
            secretName: {{ .Values.tls.secretName }}
        {{- else }}
        {{- fail "Either provide your own certificates under .Values.tls.secretName or enable the tls certManager certificate if you have cert-manager on your cluster!"}}
        {{- end }}
        {{- if .Values.indexer.config.indexerInternalUsersSecretName }}
        - name: indexer-users
          secret:
            secretName: {{ .Values.indexer.config.indexerInternalUsersSecretName }}
        {{- else }}
        - name: indexer-users
          secret:
            secretName: {{ include "wazuh.fullname" . }}-indexer-users
        {{- end }}
        {{- if .Values.indexer.config.indexerCustomConfig }}
        - name: indexer-conf
          configMap:
            name: {{ .Values.indexer.config.indexerCustomConfig }}
        {{- else }}
        - name: indexer-conf
          configMap:
            name: {{ include "wazuh.fullname" . }}-indexer-config
        {{- end }}
        {{- if .Values.indexer.storage.existingClaim }}
        - name: wazuh-indexer
          persistentVolumeClaim:
            claimName: {{ .Values.indexer.storage.existingClaim }}
        {{- end }}
      {{- with .Values.indexer.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.indexer.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.indexer.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.indexer.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  {{- if not .Values.indexer.storage.existingClaim }}
  volumeClaimTemplates:
    - metadata:
        name: wazuh-indexer
        annotations:
          helm.sh/resource-policy: keep
      spec:
        accessModes: [ "ReadWriteOnce" ]
        {{- if .Values.indexer.storage.storageClassName }}
        storageClassName: {{ .Values.indexer.storage.storageClassName }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.indexer.storage.size | required "A storage size must be specified when not using an existing claim" }}
  {{- end }}