{{- if not .Values.indexer.config.indexerInternalUsersSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wazuh.fullname" . }}-indexer-users
type: Opaque
data:
{{ (.Files.Glob "configs/indexer_conf/internal_users.yml").AsSecrets | indent 2 }}
{{- end }}
