apiVersion: v1
kind: Service
metadata:
  name: {{ include "wazuh.fullname" . }}-indexer
  labels:
    app: {{ include "wazuh.fullname" . }}-indexer
    {{- include "wazuh.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 9300
      targetPort: 9300
      protocol: TCP
      name: indexer-nodes
    - port: 9200
      targetPort: 9200
      protocol: TCP
      name: indexer-api
  selector:
    app: {{ include "wazuh.fullname" . }}-indexer
    {{- include "wazuh.selectorLabels" . | nindent 4 }}
