# Default values for kutt.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: josaorg/kutt
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

## For a full list of configuration visit https://github.com/thedevs-network/kutt/blob/develop/.docker.env
## General App Settings
general:
  siteName: "JOSA Link"
  siteDomain: "example.com"
  disallowRegistration: "true"
  disallowAnonymousLinks: "true"
  nonUserCoolDown: 0
  tlsRejectUnauthorized: 0
  ## A passphrase to encrypt JWT. Use a long and secure key.
  ## The Secret name for the jwt secret
  ## NOTE: Must contain key `jwt-secret`
  jwtSecretName: "kutt-secret"
  ## The ConfigMap name containing the admin emails
  ## NOTE: Must contain key `ADMIN_EMAILS`
  adminEmailsConfigMapName: "admin-emails"
  ## Use HTTPS for links with custom domain
  useHTTPSForCustomDomains: "false"

smtp:
  ## The email address that will receive submitted reports.
  reportEmail: "admin@example.com"
  ## Support email to show on the app
  contactEmail: "contact@example.com"
  ## Your email host details to use to send verification emails.
  ## More info on http://nodemailer.com/
  ## Mail from example "Kutt <support@kutt.it>". Leave empty to use MAIL_USER
  host: mail.example.com
  port: 587
  user: "noreply@example.com"
  mailFrom: "Kutt <noreply@example.com>"
  secure: "true"
  ## The Secret name containing the smtp password
  ## NOTE: Must contain key `smtp-password`
  smtpPasswordSecretName: "kutt-secret"

database:
  host: database-host
  name: kutt_db
  port: 25060
  ssl: "true"
  ## The Secret name containing the database credentials
  ## NOTE: Must contain key `database-password`
  ## NOTE: Must contain key `database-user`
  databaseSecretName: "kutt-secret"

redis:
  host: redis-host
  port: 6379
  ## The Secret name containing the redis password
  ## NOTE: Must contain key `redis-password`
  redisPasswordSecretName: "kutt-secret"

extraEnv:
  {}
  # ENV_VAR: "SomeValue"

extraEnvFromConfigMap:
  []
  # - kutt-extra-configMap-name

extraEnvFromSecret:
  []
  # - kutt-extra-secret-name

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext:
  {}
  # fsGroup: 2000

securityContext:
  {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations:
    {}
    # cert-manager.io/cluster-issuer: letsencrypt
    # external-dns.alpha.kubernetes.io/target: nginx-new.ingress.cloud.josa.ngo
    # external-dns.alpha.kubernetes.io/ingress-hostname-source: defined-hosts-only
  hosts:
    - host: example.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: kutt-tls
      hosts:
        - example.com

resources:
  {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

livenessProbe:
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 3

readinessProbe:
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 3
