{{- if .Values.core.extraEnv }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mailman.core.fullname" . }}-extraEnv
  labels:
    {{- include "mailman.labels" . | nindent 4 }}
data:
{{- range $envKey, $envVal := .Values.core.extraEnv }}
  {{ $envKey | upper }}: {{ $envVal | quote }}
{{- end }}

---
{{- end }}

{{- if .Values.core.postfixExtender.extraEnv }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mailman.core.fullname" . }}-postfix-extender-extraEnv
  labels:
    {{- include "mailman.labels" . | nindent 4 }}
data:
{{- range $envKey, $envVal := .Values.core.postfixExtender.extraEnv }}
  {{ $envKey | upper }}: {{ $envVal | quote }}
{{- end }}

---
{{- end }}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mailman.core.fullname" . }}
  labels:
    {{- include "mailman.labels" . | nindent 4 }}
data:
  mailman-extra.cfg: |
    [mailman]
    site_owner: {{ .Values.mailman.adminEmail }}
