{{- if .Values.core.autoscaling.enabled }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "mailman.core.fullname" . }}
  labels:
    {{- include "mailman.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "mailman.core.fullname" . }}
  minReplicas: {{ .Values.core.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.core.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.core.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: {{ .Values.core.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.core.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: {{ .Values.core.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}

---
{{- end }}

{{- if .Values.web.autoscaling.enabled }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "mailman.web.fullname" . }}
  labels:
    {{- include "mailman.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "mailman.web.fullname" . }}
  minReplicas: {{ .Values.web.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.web.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.web.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: {{ .Values.web.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.web.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: {{ .Values.web.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}

---
{{- end }}

{{- if .Values.postfix.autoscaling.enabled }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "mailman.postfix.fullname" . }}
  labels:
    {{- include "mailman.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "mailman.postfix.fullname" . }}
  minReplicas: {{ .Values.postfix.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.postfix.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.postfix.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: {{ .Values.postfix.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.postfix.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: {{ .Values.postfix.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
---
{{- end }}
