{{- if .Values.postfix.extraEnv }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mailman.postfix.fullname" . }}-extraEnv
  labels:
    {{- include "mailman.labels" . | nindent 4 }}
data:
{{- range $envKey, $envVal := .Values.postfix.extraEnv }}
  {{ $envKey | upper }}: {{ $envVal | quote }}
{{- end }}

---
{{- end }}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mailman.postfix.fullname" . }}
  labels:
    {{- include "mailman.labels" . | nindent 4 }}
data:
  configure.sh: |
    postconf -e transport_maps=tcp:{{ include "mailman.core.fullname" . }}:5000
    postconf -e local_recipient_maps=tcp:{{ include "mailman.core.fullname" . }}:5000
    postconf -e relay_domains=tcp:{{ include "mailman.core.fullname" . }}:5000
    postconf -e "mynetworks = 127.0.0.0/8 [::ffff:127.0.0.0]/104 [::1]/128 172.16.0.0/12 192.168.0.0/16 {{ .Values.postfix.subnet }}"
    postconf -X smtpd_recipient_restrictions
    postconf -e "smtpd_delay_reject = yes"
    postconf -e "smtpd_helo_required = yes"
    postconf -e "smtpd_sasl_auth_enable=yes"
    postconf -e "smtpd_reject_unlisted_recipient=yes"
    postconf -e "smtpd_client_restrictions=permit_mynetworks,reject_non_fqdn_sender,reject_unknown_sender_domain,reject_rbl_client zen.spamhaus.org,reject_rhsbl_reverse_client dbl.spamhaus.org,reject_rhsbl_helo dbl.spamhaus.org,reject_rhsbl_sender dbl.spamhaus.org,permit"
    postconf -e "smtpd_recipient_restrictions=permit_mynetworks,permit_sasl_authenticated,reject_unauth_destination,reject_rbl_client zen.spamhaus.org,reject_rhsbl_reverse_client dbl.spamhaus.org,reject_rhsbl_helo dbl.spamhaus.org,reject_rhsbl_sender dbl.spamhaus.org"
  {{- if .Values.postfix.relay }}
    cat >> /etc/postfix/sasl_passwd <<EOF
    [${RELAY_HOST}]:${RELAY_PORT}    ${RELAY_USERNAME}:${RELAY_PASSWORD}
    EOF
    postmap /etc/postfix/sasl_passwd
    chmod 0600 /etc/postfix/sasl_passwd /etc/postfix/sasl_passwd.db
    postconf -e "relayhost=[${RELAY_HOST}]:${RELAY_PORT}"
    postconf -e "smtp_sasl_auth_enable=yes"
    postconf -e "smtp_sasl_security_options=noanonymous"
    postconf -e "smtp_sasl_password_maps=hash:/etc/postfix/sasl_passwd"
  {{- end }}
  {{- if .Values.postfix.debugMode }}
    postconf -e smtpd_tls_loglevel=1
    postconf -e smtp_tls_loglevel=1
  {{- end }}
