{{- if .Values.web.extraEnv }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mailman.web.fullname" . }}-extra-env
  labels:
    {{- include "mailman.labels" . | nindent 4 }}
data:
{{- range $envKey, $envVal := .Values.web.extraEnv }}
  {{ $envKey | upper }}: {{ $envVal | quote }}
{{- end }}
---
{{- end }}

{{- if .Values.web.nginx.extraEnv }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mailman.web.fullname" . }}-nginx-extra-env
  labels:
    {{- include "mailman.labels" . | nindent 4 }}
data:
{{- range $envKey, $envVal := .Values.web.nginx.extraEnv }}
  {{ $envKey | upper }}: {{ $envVal | quote }}
{{- end }}
---
{{- end }}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mailman.web.fullname" . }}
  labels:
    {{- include "mailman.labels" . | nindent 4 }}
data:
  default.conf: |
    server {
      listen 80 default_server;
      location / {
        uwsgi_pass 127.0.0.1:8080;
        include uwsgi_params;
        uwsgi_read_timeout 300;
      }
      location /static/ {
        alias /opt/mailman-web-data/static/;
      }
    }
{{- if .Values.web.extraConfig }}
  settings_local.py:
    {{- toYaml .Values.web.extraConfig | nindent 4 }}
{{- end }}