apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "statping.fullname" . }}-env
  labels:
    {{- include "statping.labels" . | nindent 4 }}
data:
{{- range $envKey, $envVal := .Values.env }}
  {{ $envKey | upper }}: {{ $envVal | quote }}
{{- end }}
