apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "contributions-cron.fullname" . }}
  labels:
    {{- include "contributions-cron.labels" . | nindent 4 }}
spec:
  concurrencyPolicy: {{ .Values.concurrencyPolicy }}
  failedJobsHistoryLimit: {{ .Values.failedJobsHistoryLimit }}
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            cron: {{ .Values.name }}
        spec:
        {{- if hasKey .Values "serviceAccount" }}
        {{- if hasKey .Values.serviceAccount "name" }}
          serviceAccountName: {{ .Values.serviceAccount.name }}
        {{- else }}
          serviceAccountName: {{ .Values.name }}
        {{- end }}
        {{- end }}
        {{- if hasKey .Values "securityContext" }}
          {{- if .Values.securityContext.runAsUser }}
          securityContext:
            runAsUser: {{ .Values.securityContext.runAsUser }}
            {{- if .Values.securityContext.runAsGroup }}
            runAsGroup: {{ .Values.securityContext.runAsGroup }}
            {{- end }}
            {{- if .Values.securityContext.fsGroup }}
            fsGroup: {{ .Values.securityContext.fsGroup }}
            {{- end }}
          {{- end }}
        {{- end }}
          containers:
          - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            imagePullPolicy: {{ .Values.image.imagePullPolicy }}
            name: {{ .Values.name }}
            envFrom:
            - configMapRef:
                name: {{ include "contributions-cron.fullname" . }}-config
            {{- range .Values.configMapNamesforEnv }}
            - configMapRef:
                name: {{ . }}
          {{- end }}
          {{- range .Values.secretNamesForEnv }}
            - secretRef:
                name: {{ . }}
          {{- end }}
            {{- if .Values.command }}
            command: {{ .Values.command }}
            {{- end }}
            {{- with .Values.args }}
            args:
{{ toYaml . | indent 12 }}
              {{- end }}
            {{- with .Values.resources }}
            resources:
{{ toYaml . | indent 14 }}
            {{- end }}
            {{- if .Values.certificate.enabled }}
              volumeMounts:
              - mountPath: {{ .Values.certificate.path | quote }}
                name: ca-certificate
                readOnly: true
          volumes:
            - name: ca-certificate
              secret:
                secretName: {{ .Values.certificate.secret }}
            {{- end }}
          {{- with .Values.nodeSelector }}
          nodeSelector:
{{ toYaml . | indent 12 }}
          {{- end }}
          {{- with .Values.affinity }}
          affinity:
{{ toYaml . | indent 12 }}
          {{- end }}
          {{- with .Values.tolerations }}
          tolerations:
{{ toYaml . | indent 12 }}
          {{- end }}
          restartPolicy: {{ .Values.restartPolicy }}
          {{- with .Values.volumes }}
          volumes:
{{ toYaml . | indent 12 }}
          {{- end }}
  schedule: {{ .Values.schedule | quote }}
  successfulJobsHistoryLimit: {{ .Values.successfulJobsHistoryLimit }}