apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "safepass.fullname" . }}-config
  labels:
    {{- include "safepass.labels" . | nindent 4 }}
data:
  DEBUG: {{ .Values.general.debug | quote }}
  REDIS_PREFIX: {{ .Values.redis.redisPrefix | quote }}
  {{- range $key, $value := .Values.extraEnv }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
